# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: mc-ctl

builds:
  - id: mc-ctl
    main: ./cmd/mc-ctl
    binary: mc-ctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README*

checksum:
  name_template: checksums.txt

release:
  make_latest: true
